services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "32400:32400"
      - "1900:1900/udp"
      - "3005:3005"
      - "5353:5353/udp"
      - "8324:8324"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "32469:32469"
    env_file: .env
    environment:
      - VERSION=docker
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - "$BASE_FOLDER/config/plex:/config"
      - "$BASE_FOLDER/media:/media"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - 8989:8989
    env_file: .env
    volumes:
      - "$BASE_FOLDER/config/sonarr:/config"
      - "$BASE_FOLDER/media:/media"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - 7878:7878
    env_file: .env
    volumes:
      - "$BASE_FOLDER/config/radarr:/config"
      - "$BASE_FOLDER/media:/media"

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    env_file: .env
    volumes:
      - "$BASE_FOLDER/config/deluge:/config"
      - "$BASE_FOLDER/media:/media"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - 9696:9696
    env_file: .env
    volumes:
      - "$BASE_FOLDER/config/prowlarr:/config"

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    pull_policy: always
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    env_file: .env
    volumes:
      - "$BASE_FOLDER/config/heimdall:/config"

  caddy:
    build:
      context: ./caddy
      pull: true
    pull_policy: build
    restart: unless-stopped
    environment:
      CF_API_TOKEN: $CF_API_TOKEN
      BASE_DOMAIN: $BASE_DOMAIN
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "$BASE_FOLDER/config/caddy/data:/data"
      - "$BASE_FOLDER/config/caddy/config:/config"

  xteve:
    image: docker.io/alturismo/xteve:latest
    pull_policy: always
    restart: unless-stopped
    env_file: .env
    ports:
      - "34400:34400"
    volumes:
      - "$BASE_FOLDER/config/xteve/data:/root/.xteve"
      - "$BASE_FOLDER/config/xteve/config:/config"

  stremio:
    image: docker.io/stremio/server:latest
    pull_policy: always
    restart: unless-stopped
    env_file: .env
    environment:
      - "NO_CORS=1"
    ports:
      - "11470:11470"
