name: Build artifacts

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * 0" # on Sundays at 4am UTC

concurrency:
  group: main-branch-build
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io

jobs:
  build-docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        image:
          - context: "./mediacenter/caddy"
            name: "${{ github.repository }}-caddy"
          - context: "./system"
            name: "${{ github.repository }}-system"

    name: Build and push ${{ matrix.image.name }}

    steps:
      - uses: actions/checkout@v5

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ matrix.image.name}}
          tags: |
            type=raw,value=latest
            type=schedule
            type=sha

      - uses: docker/build-push-action@v6
        id: build-and-push
        with:
          context: ${{ matrix.image.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
