name: Prune old package versions

on:
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  prune:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - "${{ github.repository }}-caddy"
          - "${{ github.repository }}-system"

    name: Prune old versions of ${{ matrix.image }}

    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.image }}
          package-type: "container"
          min-versions-to-keep: 10
